version: '3.9'

services:
  web:
    build: .
    container_name: coffeeclub_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Optional: für Live-Code-Änderungen beim Entwickeln
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
