###
POST http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "small",
    "specialdrinks": true, 
    "priceperweek": 7,
    "amount": 3
}

### second abomodel
POST http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "small+",
    "specialdrinks": true, 
    "priceperweek": 10,
    "amount": 3
}

### 
POST http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "medium",
    "specialdrinks": false, 
    "priceperweek": 11,
    "amount": 5
}

### 
POST http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "medium+",
    "specialdrinks": true, 
    "priceperweek": 19,
    "amount": 5
}

### 
POST http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "large",
    "specialdrinks": false, 
    "priceperweek": 15,
    "amount": 7
}

### 
POST http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "large+",
    "specialdrinks": true, 
    "priceperweek": 22,
    "amount": 7
}

### 
POST http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "unlimited",
    "specialdrinks": false, 
    "priceperweek": 30,
    "amount": 999
}

### 
POST http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "unlimited+",
    "specialdrinks": true, 
    "priceperweek": 40,
    "amount": 999
}
### change model details (-> for price adjustments)
# only for adjustment purposes during development
PATCH http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "small",
    "specialdrinks": false, 
    "priceperweek": 7,
    "amount": 3
}

### get all models
GET http://localhost:8000/abomodels/

### get by id
GET  http://localhost:8000/abomodels/small

### post weird model
POST http://localhost:8000/abomodels/
Content-Type: application/json

{
    "id": "hhasas",
    "specialdrinks": true, 
    "priceperweek": 333,
    "amount": 32
}

### Delete with id
DELETE http://localhost:8000/abomodels/hhasas