POST http://localhost:8000/cafes/
Content-Type: application/json

{
  "id": "Café am Rande der Welt",
  "iban": "DE44500105175407324931",
  "bic": "DEUTDEFF",
  "account_holder": "café am rande der welt",
  "abomodels": ["small", "small+"]
}

###
GET http://localhost:8000/cafes/

### 
GET http://localhost:8000/cafes/Café_am_Rande_der_Welt/abo

###
DELETE http://localhost:8000/cafes/Café_am_Rande_der_Welt

###
PATCH http://localhost:8000/cafes/
Content-Type: application/json

{
  "id": "Café am Rande der Welt",
  "iban": "DE97 2014 1177 2007 1112 45",
  "bic": "COBADEH88",
  "account_holder": "café am rande der welt",
  "abomodels": ["small", "small+"]
}