
POST http://localhost:8000/cafes
Content-Type: application/json

{
  "id": 1,
  "name": "Café am Rande der Welt",
  "street": "Randstraße",
  "housenumber": 11,
  "town": "Weltstadt", 
  "zip": "77777",
  "adminmail": "cafe@mail.com"
}
### add second cafe

POST http://localhost:8000/cafes
Content-Type: application/json

{
  "id": 2,
  "name": "Café am Rande des Universums",
  "street": "Randstraße",
  "housenumber": 12,
  "town": "Milchstadt", 
  "zip": "71111",
  "adminmail": "caf2@mail.com"
}

### get all cafes
GET http://localhost:8000/cafes

### post first new cafe
POST http://localhost:8000/cafes
Content-Type: application/json

{
  "id": 1,
  "name": "Café am Rande der Welt",
  "street": "Randstraße",
  "housenumber": 11,
  "town": "Weltstadt", 
  "zip": "77777",
  "adminmail": "cafe@mail.com"
}

###
GET http://localhost:8000/cafes/