POST http://localhost:8000/employee/signup
Content-Type: application/json

{
    "id": 2,
    "cafe_id": 2,
    "name": "Luisa Löser",
    "email": "lui@mail.com",
    "password": "newpassword",
    "sudo": false
}
